import type { LessonProgram } from '../../types';

export const binary_search: LessonProgram = {
  id: 'binary_search', language: 'python', topic: 'searching_sorting', lessonNumber: 2,
  friendlyName: 'Binary Search',
  learningObjective: 'Learn how binary search repeatedly divides a sorted array in half to find a target.',
  lines: [
    { lineNum: 1, tokens: [{ type: 'variable', value: 'arr' }, { type: 'text', value: ' ' }, { type: 'operator', value: '=' }, { type: 'text', value: ' ' }, { type: 'punctuation', value: '[' }, { type: 'number', value: '10' }, { type: 'punctuation', value: ',' }, { type: 'text', value: ' ' }, { type: 'number', value: '20' }, { type: 'punctuation', value: ',' }, { type: 'text', value: ' ' }, { type: 'number', value: '30' }, { type: 'punctuation', value: ',' }, { type: 'text', value: ' ' }, { type: 'number', value: '40' }, { type: 'punctuation', value: ',' }, { type: 'text', value: ' ' }, { type: 'number', value: '50' }, { type: 'punctuation', value: ',' }, { type: 'text', value: ' ' }, { type: 'number', value: '60' }, { type: 'punctuation', value: ']' }] },
    { lineNum: 2, tokens: [{ type: 'variable', value: 'target' }, { type: 'text', value: ' ' }, { type: 'operator', value: '=' }, { type: 'text', value: ' ' }, { type: 'number', value: '50' }] },
    { lineNum: 3, tokens: [{ type: 'variable', value: 'low' }, { type: 'text', value: ' ' }, { type: 'operator', value: '=' }, { type: 'text', value: ' ' }, { type: 'number', value: '0' }] },
    { lineNum: 4, tokens: [{ type: 'variable', value: 'high' }, { type: 'text', value: ' ' }, { type: 'operator', value: '=' }, { type: 'text', value: ' ' }, { type: 'function', value: 'len' }, { type: 'punctuation', value: '(' }, { type: 'variable', value: 'arr' }, { type: 'punctuation', value: ')' }, { type: 'text', value: ' ' }, { type: 'operator', value: '-' }, { type: 'text', value: ' ' }, { type: 'number', value: '1' }] },
    { lineNum: 5, tokens: [{ type: 'keyword', value: 'while' }, { type: 'text', value: ' ' }, { type: 'variable', value: 'low' }, { type: 'text', value: ' ' }, { type: 'operator', value: '<=' }, { type: 'text', value: ' ' }, { type: 'variable', value: 'high' }, { type: 'punctuation', value: ':' }] },
    { lineNum: 6, tokens: [{ type: 'text', value: '    ' }, { type: 'variable', value: 'mid' }, { type: 'text', value: ' ' }, { type: 'operator', value: '=' }, { type: 'text', value: ' ' }, { type: 'punctuation', value: '(' }, { type: 'variable', value: 'low' }, { type: 'text', value: ' ' }, { type: 'operator', value: '+' }, { type: 'text', value: ' ' }, { type: 'variable', value: 'high' }, { type: 'punctuation', value: ')' }, { type: 'text', value: ' ' }, { type: 'operator', value: '//' }, { type: 'text', value: ' ' }, { type: 'number', value: '2' }] },
    { lineNum: 7, tokens: [{ type: 'text', value: '    ' }, { type: 'keyword', value: 'if' }, { type: 'text', value: ' ' }, { type: 'variable', value: 'arr' }, { type: 'punctuation', value: '[' }, { type: 'variable', value: 'mid' }, { type: 'punctuation', value: ']' }, { type: 'text', value: ' ' }, { type: 'operator', value: '==' }, { type: 'text', value: ' ' }, { type: 'variable', value: 'target' }, { type: 'punctuation', value: ':' }] },
    { lineNum: 8, tokens: [{ type: 'text', value: '        ' }, { type: 'function', value: 'print' }, { type: 'punctuation', value: '(' }, { type: 'string', value: 'f"Found at index {mid}"' }, { type: 'punctuation', value: ')' }] },
    { lineNum: 9, tokens: [{ type: 'text', value: '        ' }, { type: 'keyword', value: 'break' }] },
    { lineNum: 10, tokens: [{ type: 'text', value: '    ' }, { type: 'keyword', value: 'elif' }, { type: 'text', value: ' ' }, { type: 'variable', value: 'arr' }, { type: 'punctuation', value: '[' }, { type: 'variable', value: 'mid' }, { type: 'punctuation', value: ']' }, { type: 'text', value: ' ' }, { type: 'operator', value: '<' }, { type: 'text', value: ' ' }, { type: 'variable', value: 'target' }, { type: 'punctuation', value: ':' }] },
    { lineNum: 11, tokens: [{ type: 'text', value: '        ' }, { type: 'variable', value: 'low' }, { type: 'text', value: ' ' }, { type: 'operator', value: '=' }, { type: 'text', value: ' ' }, { type: 'variable', value: 'mid' }, { type: 'text', value: ' ' }, { type: 'operator', value: '+' }, { type: 'text', value: ' ' }, { type: 'number', value: '1' }] },
    { lineNum: 12, tokens: [{ type: 'text', value: '    ' }, { type: 'keyword', value: 'else' }, { type: 'punctuation', value: ':' }] },
    { lineNum: 13, tokens: [{ type: 'text', value: '        ' }, { type: 'variable', value: 'high' }, { type: 'text', value: ' ' }, { type: 'operator', value: '=' }, { type: 'text', value: ' ' }, { type: 'variable', value: 'mid' }, { type: 'text', value: ' ' }, { type: 'operator', value: '-' }, { type: 'text', value: ' ' }, { type: 'number', value: '1' }] },
  ],
  executionSteps: [
    { step: 1, lineNum: 1, explanationEnglish: 'Initialize sorted array.', explanationHinglish: 'Sorted array banaya.', memorySnapshot: { arr: '"[10, 20, 30, 40, 50, 60]"' }, animationEvent: { type: 'CREATE_VARIABLE', name: 'arr', value: '"[10, 20, 30, 40, 50, 60]"' } },
    { step: 2, lineNum: 2, explanationEnglish: 'Set target to search.', explanationHinglish: 'Target set kiya.', memorySnapshot: { arr: '"[10, 20, 30, 40, 50, 60]"', target: 50 }, animationEvent: { type: 'CREATE_VARIABLE', name: 'target', value: 50 } },
    { step: 3, lineNum: 3, explanationEnglish: 'Set low pointer.', explanationHinglish: 'Low pointer set kiya.', memorySnapshot: { arr: '"[10, 20, 30, 40, 50, 60]"', target: 50, low: 0 }, animationEvent: { type: 'CREATE_VARIABLE', name: 'low', value: 0 } },
    { step: 4, lineNum: 4, explanationEnglish: 'Set high pointer.', explanationHinglish: 'High pointer set kiya.', memorySnapshot: { arr: '"[10, 20, 30, 40, 50, 60]"', target: 50, low: 0, high: 5 }, animationEvent: { type: 'CREATE_VARIABLE', name: 'high', value: 5 } },
    { step: 5, lineNum: 5, explanationEnglish: 'Check if low <= high.', explanationHinglish: 'Check kiya kya low <= high hai.', memorySnapshot: { arr: '"[10, 20, 30, 40, 50, 60]"', target: 50, low: 0, high: 5 }, animationEvent: { type: 'NONE' } },
    { step: 6, lineNum: 6, explanationEnglish: 'Calculate mid pointer.', explanationHinglish: 'Mid pointer calculate kiya.', memorySnapshot: { arr: '"[10, 20, 30, 40, 50, 60]"', target: 50, low: 0, high: 5, mid: 2 }, animationEvent: { type: 'CREATE_VARIABLE', name: 'mid', value: 2 } },
    { step: 7, lineNum: 7, explanationEnglish: 'Check if mid element matches target.', explanationHinglish: 'Check kiya kya mid element target hai.', memorySnapshot: { arr: '"[10, 20, 30, 40, 50, 60]"', target: 50, low: 0, high: 5, mid: 2 }, animationEvent: { type: 'NONE' } },
    { step: 8, lineNum: 10, explanationEnglish: 'Check if mid is less than target.', explanationHinglish: 'Check kiya kya mid target se chhota hai.', memorySnapshot: { arr: '"[10, 20, 30, 40, 50, 60]"', target: 50, low: 0, high: 5, mid: 2 }, animationEvent: { type: 'NONE' } },
    { step: 9, lineNum: 11, explanationEnglish: 'Move low pointer right.', explanationHinglish: 'Low pointer ko right move kiya.', memorySnapshot: { arr: '"[10, 20, 30, 40, 50, 60]"', target: 50, low: 3, high: 5, mid: 2 }, animationEvent: { type: 'UPDATE_VARIABLE', name: 'low', oldValue: 0, newValue: 3 } },
    { step: 10, lineNum: 5, explanationEnglish: 'Check if low <= high.', explanationHinglish: 'Check kiya kya low <= high hai.', memorySnapshot: { arr: '"[10, 20, 30, 40, 50, 60]"', target: 50, low: 3, high: 5 }, animationEvent: { type: 'NONE' } },
    { step: 11, lineNum: 6, explanationEnglish: 'Calculate mid pointer.', explanationHinglish: 'Mid pointer calculate kiya.', memorySnapshot: { arr: '"[10, 20, 30, 40, 50, 60]"', target: 50, low: 3, high: 5, mid: 4 }, animationEvent: { type: 'CREATE_VARIABLE', name: 'mid', value: 4 } },
    { step: 12, lineNum: 7, explanationEnglish: 'Check if mid element matches target.', explanationHinglish: 'Check kiya kya mid element target hai.', memorySnapshot: { arr: '"[10, 20, 30, 40, 50, 60]"', target: 50, low: 3, high: 5, mid: 4 }, animationEvent: { type: 'NONE' } },
    { step: 13, lineNum: 8, explanationEnglish: 'Target found at mid!', explanationHinglish: 'Target mid par mil gaya!', memorySnapshot: { arr: '"[10, 20, 30, 40, 50, 60]"', target: 50, low: 3, high: 5, mid: 4 }, consoleOutput: 'Found at index 4', animationEvent: { type: 'PRINT_VALUE', variableName: 'mid', outputValue: '"Found at index 4"' } },
    { step: 14, lineNum: 9, explanationEnglish: 'Break the loop.', explanationHinglish: 'Loop break kiya.', memorySnapshot: { arr: '"[10, 20, 30, 40, 50, 60]"', target: 50, low: 3, high: 5, mid: 4 }, animationEvent: { type: 'NONE' } }
  ],
};