import type { LessonProgram } from '../../types';

export const linear_search: LessonProgram = {
  id: 'linear_search', language: 'python', topic: 'searching_sorting', lessonNumber: 1,
  friendlyName: 'Linear Search',
  learningObjective: 'Learn how linear search iterates sequentially to find a target.',
  lines: [
    { lineNum: 1, tokens: [{ type: 'variable', value: 'arr' }, { type: 'text', value: ' ' }, { type: 'operator', value: '=' }, { type: 'text', value: ' ' }, { type: 'punctuation', value: '[' }, { type: 'number', value: '12' }, { type: 'punctuation', value: ',' }, { type: 'text', value: ' ' }, { type: 'number', value: '25' }, { type: 'punctuation', value: ',' }, { type: 'text', value: ' ' }, { type: 'number', value: '18' }, { type: 'punctuation', value: ',' }, { type: 'text', value: ' ' }, { type: 'number', value: '40' }, { type: 'punctuation', value: ',' }, { type: 'text', value: ' ' }, { type: 'number', value: '15' }, { type: 'punctuation', value: ']' }] },
    { lineNum: 2, tokens: [{ type: 'variable', value: 'target' }, { type: 'text', value: ' ' }, { type: 'operator', value: '=' }, { type: 'text', value: ' ' }, { type: 'number', value: '40' }] },
    { lineNum: 3, tokens: [{ type: 'variable', value: 'found' }, { type: 'text', value: ' ' }, { type: 'operator', value: '=' }, { type: 'text', value: ' ' }, { type: 'keyword', value: 'False' }] },
    { lineNum: 4, tokens: [{ type: 'keyword', value: 'for' }, { type: 'text', value: ' ' }, { type: 'variable', value: 'i' }, { type: 'text', value: ' ' }, { type: 'keyword', value: 'in' }, { type: 'text', value: ' ' }, { type: 'function', value: 'range' }, { type: 'punctuation', value: '(' }, { type: 'function', value: 'len' }, { type: 'punctuation', value: '(' }, { type: 'variable', value: 'arr' }, { type: 'punctuation', value: ')' }, { type: 'punctuation', value: ')' }, { type: 'punctuation', value: ':' }] },
    { lineNum: 5, tokens: [{ type: 'text', value: '    ' }, { type: 'keyword', value: 'if' }, { type: 'text', value: ' ' }, { type: 'variable', value: 'arr' }, { type: 'punctuation', value: '[' }, { type: 'variable', value: 'i' }, { type: 'punctuation', value: ']' }, { type: 'text', value: ' ' }, { type: 'operator', value: '==' }, { type: 'text', value: ' ' }, { type: 'variable', value: 'target' }, { type: 'punctuation', value: ':' }] },
    { lineNum: 6, tokens: [{ type: 'text', value: '        ' }, { type: 'variable', value: 'found' }, { type: 'text', value: ' ' }, { type: 'operator', value: '=' }, { type: 'text', value: ' ' }, { type: 'keyword', value: 'True' }] },
    { lineNum: 7, tokens: [{ type: 'text', value: '        ' }, { type: 'function', value: 'print' }, { type: 'punctuation', value: '(' }, { type: 'string', value: 'f"Found at index {i}"' }, { type: 'punctuation', value: ')' }] },
    { lineNum: 8, tokens: [{ type: 'text', value: '        ' }, { type: 'keyword', value: 'break' }] },
    { lineNum: 9, tokens: [{ type: 'keyword', value: 'if' }, { type: 'text', value: ' ' }, { type: 'keyword', value: 'not' }, { type: 'text', value: ' ' }, { type: 'variable', value: 'found' }, { type: 'punctuation', value: ':' }] },
    { lineNum: 10, tokens: [{ type: 'text', value: '    ' }, { type: 'function', value: 'print' }, { type: 'punctuation', value: '(' }, { type: 'string', value: '"Not found"' }, { type: 'punctuation', value: ')' }] },
  ],
  executionSteps: [
    { step: 1, lineNum: 1, explanationEnglish: 'Initialize the array.', explanationHinglish: 'Array banaya.', memorySnapshot: { arr: '"[12, 25, 18, 40, 15]"' }, animationEvent: { type: 'CREATE_VARIABLE', name: 'arr', value: '"[12, 25, 18, 40, 15]"' } },
    { step: 2, lineNum: 2, explanationEnglish: 'Set search target.', explanationHinglish: 'Search target set kiya.', memorySnapshot: { arr: '"[12, 25, 18, 40, 15]"', target: 40 }, animationEvent: { type: 'CREATE_VARIABLE', name: 'target', value: 40 } },
    { step: 3, lineNum: 3, explanationEnglish: 'Initialize found flag to False.', explanationHinglish: 'found flag False kiya.', memorySnapshot: { arr: '"[12, 25, 18, 40, 15]"', target: 40, found: 'False' }, animationEvent: { type: 'CREATE_VARIABLE', name: 'found', value: '"False"' } },
    { step: 4, lineNum: 4, explanationEnglish: 'Start loop index 0.', explanationHinglish: 'Index 0 pe loop.', memorySnapshot: { arr: '"[12, 25, 18, 40, 15]"', target: 40, found: 'False', i: 0 }, animationEvent: { type: 'CREATE_VARIABLE', name: 'i', value: 0 } },
    { step: 5, lineNum: 5, explanationEnglish: 'Check if current element matches target.', explanationHinglish: 'Check kiya kya element target se match hota hai.', memorySnapshot: { arr: '"[12, 25, 18, 40, 15]"', target: 40, found: 'False', i: 0 }, animationEvent: { type: 'NONE' } },
    { step: 6, lineNum: 4, explanationEnglish: 'Start loop index 1.', explanationHinglish: 'Index 1 pe loop.', memorySnapshot: { arr: '"[12, 25, 18, 40, 15]"', target: 40, found: 'False', i: 1 }, animationEvent: { type: 'CREATE_VARIABLE', name: 'i', value: 1 } },
    { step: 7, lineNum: 5, explanationEnglish: 'Check if current element matches target.', explanationHinglish: 'Check kiya kya element target se match hota hai.', memorySnapshot: { arr: '"[12, 25, 18, 40, 15]"', target: 40, found: 'False', i: 1 }, animationEvent: { type: 'NONE' } },
    { step: 8, lineNum: 4, explanationEnglish: 'Start loop index 2.', explanationHinglish: 'Index 2 pe loop.', memorySnapshot: { arr: '"[12, 25, 18, 40, 15]"', target: 40, found: 'False', i: 2 }, animationEvent: { type: 'CREATE_VARIABLE', name: 'i', value: 2 } },
    { step: 9, lineNum: 5, explanationEnglish: 'Check if current element matches target.', explanationHinglish: 'Check kiya kya element target se match hota hai.', memorySnapshot: { arr: '"[12, 25, 18, 40, 15]"', target: 40, found: 'False', i: 2 }, animationEvent: { type: 'NONE' } },
    { step: 10, lineNum: 4, explanationEnglish: 'Start loop index 3.', explanationHinglish: 'Index 3 pe loop.', memorySnapshot: { arr: '"[12, 25, 18, 40, 15]"', target: 40, found: 'False', i: 3 }, animationEvent: { type: 'CREATE_VARIABLE', name: 'i', value: 3 } },
    { step: 11, lineNum: 5, explanationEnglish: 'Check if current element matches target.', explanationHinglish: 'Check kiya kya element target se match hota hai.', memorySnapshot: { arr: '"[12, 25, 18, 40, 15]"', target: 40, found: 'False', i: 3 }, animationEvent: { type: 'NONE' } },
    { step: 12, lineNum: 6, explanationEnglish: 'Match found! Set found flag to True.', explanationHinglish: 'Match mil gaya! found ko True kiya.', memorySnapshot: { arr: '"[12, 25, 18, 40, 15]"', target: 40, found: 'True', i: 3 }, animationEvent: { type: 'UPDATE_VARIABLE', name: 'found', oldValue: '"False"', newValue: '"True"' } },
    { step: 13, lineNum: 7, explanationEnglish: 'Print success message.', explanationHinglish: 'Success message print kiya.', memorySnapshot: { arr: '"[12, 25, 18, 40, 15]"', target: 40, found: 'True', i: 3 }, consoleOutput: 'Found at index 3', animationEvent: { type: 'PRINT_VALUE', variableName: 'i', outputValue: '"Found at index 3"' } },
    { step: 14, lineNum: 8, explanationEnglish: 'Break the loop.', explanationHinglish: 'Loop break kiya.', memorySnapshot: { arr: '"[12, 25, 18, 40, 15]"', target: 40, found: 'True', i: 3 }, animationEvent: { type: 'NONE' } },
    { step: 15, lineNum: 9, explanationEnglish: 'Check if found is False.', explanationHinglish: 'Check kiya kya found False hai.', memorySnapshot: { arr: '"[12, 25, 18, 40, 15]"', target: 40, found: 'True', i: 3 }, animationEvent: { type: 'NONE' } }
  ],
};