import type { LessonProgram } from '../../types';

export const print_10_to_1: LessonProgram = {
  id: 'print_10_to_1', language: 'python', topic: 'for_loop', lessonNumber: 2,
  friendlyName: 'Print Numbers (10 to 1)',
  learningObjective: 'Learn how to use a negative step in a range function to loop backwards.',
  lines: [
    { lineNum: 1, tokens: [{ type: 'keyword', value: 'for' }, { type: 'text', value: ' ' }, { type: 'variable', value: 'i' }, { type: 'text', value: ' ' }, { type: 'keyword', value: 'in' }, { type: 'text', value: ' ' }, { type: 'function', value: 'range' }, { type: 'punctuation', value: '(' }, { type: 'number', value: '10' }, { type: 'punctuation', value: ',' }, { type: 'text', value: ' ' }, { type: 'number', value: '0' }, { type: 'punctuation', value: ',' }, { type: 'text', value: ' ' }, { type: 'operator', value: '-' }, { type: 'number', value: '1' }, { type: 'punctuation', value: ')' }, { type: 'punctuation', value: ':' }] },
    { lineNum: 2, tokens: [{ type: 'text', value: '    ' }, { type: 'function', value: 'print' }, { type: 'punctuation', value: '(' }, { type: 'variable', value: 'i' }, { type: 'punctuation', value: ')' }] },
  ],
  executionSteps: [
    {
      step: 1, lineNum: 1,
      explanationEnglish: 'The loop variable "i" takes the value 10. The step is -1.',
      explanationHinglish: 'Loop variable "i" ne 10 value li.',
      memorySnapshot: { i: 10 },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'i', value: 10 },
    },
    {
      step: 2, lineNum: 2,
      explanationEnglish: 'Print the current value of "i".',
      explanationHinglish: '"i" ki current value print kiya.',
      memorySnapshot: { i: 10 },
      consoleOutput: `10`,
      animationEvent: { type: 'PRINT_VALUE', variableName: 'i', outputValue: 10 },
    },
    {
      step: 3, lineNum: 1,
      explanationEnglish: 'The loop variable "i" takes the value 9. The step is -1.',
      explanationHinglish: 'Loop variable "i" ne 9 value li.',
      memorySnapshot: { i: 9 },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'i', value: 9 },
    },
    {
      step: 4, lineNum: 2,
      explanationEnglish: 'Print the current value of "i".',
      explanationHinglish: '"i" ki current value print kiya.',
      memorySnapshot: { i: 9 },
      consoleOutput: `10\n9`,
      animationEvent: { type: 'PRINT_VALUE', variableName: 'i', outputValue: 9 },
    },
    {
      step: 5, lineNum: 1,
      explanationEnglish: 'The loop variable "i" takes the value 8. The step is -1.',
      explanationHinglish: 'Loop variable "i" ne 8 value li.',
      memorySnapshot: { i: 8 },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'i', value: 8 },
    },
    {
      step: 6, lineNum: 2,
      explanationEnglish: 'Print the current value of "i".',
      explanationHinglish: '"i" ki current value print kiya.',
      memorySnapshot: { i: 8 },
      consoleOutput: `10\n9\n8`,
      animationEvent: { type: 'PRINT_VALUE', variableName: 'i', outputValue: 8 },
    },
    {
      step: 7, lineNum: 1,
      explanationEnglish: 'The loop variable "i" takes the value 7. The step is -1.',
      explanationHinglish: 'Loop variable "i" ne 7 value li.',
      memorySnapshot: { i: 7 },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'i', value: 7 },
    },
    {
      step: 8, lineNum: 2,
      explanationEnglish: 'Print the current value of "i".',
      explanationHinglish: '"i" ki current value print kiya.',
      memorySnapshot: { i: 7 },
      consoleOutput: `10\n9\n8\n7`,
      animationEvent: { type: 'PRINT_VALUE', variableName: 'i', outputValue: 7 },
    },
    {
      step: 9, lineNum: 1,
      explanationEnglish: 'The loop variable "i" takes the value 6. The step is -1.',
      explanationHinglish: 'Loop variable "i" ne 6 value li.',
      memorySnapshot: { i: 6 },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'i', value: 6 },
    },
    {
      step: 10, lineNum: 2,
      explanationEnglish: 'Print the current value of "i".',
      explanationHinglish: '"i" ki current value print kiya.',
      memorySnapshot: { i: 6 },
      consoleOutput: `10\n9\n8\n7\n6`,
      animationEvent: { type: 'PRINT_VALUE', variableName: 'i', outputValue: 6 },
    },
    {
      step: 11, lineNum: 1,
      explanationEnglish: 'The loop variable "i" takes the value 5. The step is -1.',
      explanationHinglish: 'Loop variable "i" ne 5 value li.',
      memorySnapshot: { i: 5 },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'i', value: 5 },
    },
    {
      step: 12, lineNum: 2,
      explanationEnglish: 'Print the current value of "i".',
      explanationHinglish: '"i" ki current value print kiya.',
      memorySnapshot: { i: 5 },
      consoleOutput: `10\n9\n8\n7\n6\n5`,
      animationEvent: { type: 'PRINT_VALUE', variableName: 'i', outputValue: 5 },
    },
    {
      step: 13, lineNum: 1,
      explanationEnglish: 'The loop variable "i" takes the value 4. The step is -1.',
      explanationHinglish: 'Loop variable "i" ne 4 value li.',
      memorySnapshot: { i: 4 },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'i', value: 4 },
    },
    {
      step: 14, lineNum: 2,
      explanationEnglish: 'Print the current value of "i".',
      explanationHinglish: '"i" ki current value print kiya.',
      memorySnapshot: { i: 4 },
      consoleOutput: `10\n9\n8\n7\n6\n5\n4`,
      animationEvent: { type: 'PRINT_VALUE', variableName: 'i', outputValue: 4 },
    },
    {
      step: 15, lineNum: 1,
      explanationEnglish: 'The loop variable "i" takes the value 3. The step is -1.',
      explanationHinglish: 'Loop variable "i" ne 3 value li.',
      memorySnapshot: { i: 3 },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'i', value: 3 },
    },
    {
      step: 16, lineNum: 2,
      explanationEnglish: 'Print the current value of "i".',
      explanationHinglish: '"i" ki current value print kiya.',
      memorySnapshot: { i: 3 },
      consoleOutput: `10\n9\n8\n7\n6\n5\n4\n3`,
      animationEvent: { type: 'PRINT_VALUE', variableName: 'i', outputValue: 3 },
    },
    {
      step: 17, lineNum: 1,
      explanationEnglish: 'The loop variable "i" takes the value 2. The step is -1.',
      explanationHinglish: 'Loop variable "i" ne 2 value li.',
      memorySnapshot: { i: 2 },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'i', value: 2 },
    },
    {
      step: 18, lineNum: 2,
      explanationEnglish: 'Print the current value of "i".',
      explanationHinglish: '"i" ki current value print kiya.',
      memorySnapshot: { i: 2 },
      consoleOutput: `10\n9\n8\n7\n6\n5\n4\n3\n2`,
      animationEvent: { type: 'PRINT_VALUE', variableName: 'i', outputValue: 2 },
    },
    {
      step: 19, lineNum: 1,
      explanationEnglish: 'The loop variable "i" takes the value 1. The step is -1.',
      explanationHinglish: 'Loop variable "i" ne 1 value li.',
      memorySnapshot: { i: 1 },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'i', value: 1 },
    },
    {
      step: 20, lineNum: 2,
      explanationEnglish: 'Print the current value of "i".',
      explanationHinglish: '"i" ki current value print kiya.',
      memorySnapshot: { i: 1 },
      consoleOutput: `10\n9\n8\n7\n6\n5\n4\n3\n2\n1`,
      animationEvent: { type: 'PRINT_VALUE', variableName: 'i', outputValue: 1 },
    }
  ],
};