export enum EventCategory {
  LIFECYCLE = 'LIFECYCLE',
  EXECUTION = 'EXECUTION',
  MEMORY = 'MEMORY',
  OUTPUT = 'OUTPUT',
  UI = 'UI',
  SYSTEM = 'SYSTEM'
}

export enum EventType {
  // Lifecycle
  PROGRAM_LOADED = 'PROGRAM_LOADED',
  PROGRAM_RESET = 'PROGRAM_RESET',
  LESSON_STARTED = 'LESSON_STARTED',
  LESSON_FINISHED = 'LESSON_FINISHED',

  // Execution
  EXECUTION_STARTED = 'EXECUTION_STARTED',
  EXECUTION_PAUSED = 'EXECUTION_PAUSED',
  EXECUTION_RESUMED = 'EXECUTION_RESUMED',
  EXECUTION_STOPPED = 'EXECUTION_STOPPED',
  EXECUTION_COMPLETED = 'EXECUTION_COMPLETED',
  STEP_STARTED = 'STEP_STARTED',
  STEP_FINISHED = 'STEP_FINISHED',
  SUBSTEP_STARTED = 'SUBSTEP_STARTED',
  SUBSTEP_FINISHED = 'SUBSTEP_FINISHED',
  LINE_CHANGED = 'LINE_CHANGED',
  CONDITION_EVALUATED = 'CONDITION_EVALUATED',
  LOOP_STARTED = 'LOOP_STARTED',
  LOOP_ITERATION = 'LOOP_ITERATION',
  LOOP_FINISHED = 'LOOP_FINISHED',
  FUNCTION_CALLED = 'FUNCTION_CALLED',
  FUNCTION_RETURNED = 'FUNCTION_RETURNED',
  STACK_PUSH = 'STACK_PUSH',
  STACK_POP = 'STACK_POP',

  // Memory
  VARIABLE_CREATED = 'VARIABLE_CREATED',
  VARIABLE_UPDATED = 'VARIABLE_UPDATED',
  VARIABLE_DELETED = 'VARIABLE_DELETED',
  VARIABLE_READ = 'VARIABLE_READ',
  ARRAY_CREATED = 'ARRAY_CREATED',
  ARRAY_UPDATED = 'ARRAY_UPDATED',
  ARRAY_ACCESSED = 'ARRAY_ACCESSED',
  MEMORY_CELL_CREATED = 'MEMORY_CELL_CREATED',
  MEMORY_CELL_UPDATED = 'MEMORY_CELL_UPDATED',

  // Output
  OUTPUT_APPENDED = 'OUTPUT_APPENDED',
  OUTPUT_CLEARED = 'OUTPUT_CLEARED',

  // UI / Parameters
  PARAMETER_CHANGED = 'PARAMETER_CHANGED',
  EXPLANATION_UPDATED = 'EXPLANATION_UPDATED',
  TIMELINE_UPDATED = 'TIMELINE_UPDATED',
  HIGHLIGHT_LINE = 'HIGHLIGHT_LINE',

  // System (Future/Extensibility)
  ERROR_THROWN = 'ERROR_THROWN',
  WARNING_ISSUED = 'WARNING_ISSUED',
  AUDIO_TRIGGERED = 'AUDIO_TRIGGERED',
  CAMERA_MOVED = 'CAMERA_MOVED',
  TOOLTIP_SHOWN = 'TOOLTIP_SHOWN'
}

export enum EventPriority {
  LOW = 0,
  NORMAL = 1,
  HIGH = 2,
  CRITICAL = 3
}
