export const DesignTokens = {
  colors: {
    primary: {
      light: 'var(--color-primary-light)',
      default: 'var(--color-primary)',
      hover: 'var(--color-primary-hover)',
      active: 'var(--color-primary-active)',
    },
    background: {
      default: 'var(--color-background)',
      paper: 'var(--color-background-paper)',
      elevated: 'var(--color-background-elevated)',
      glass: 'var(--color-background-glass)',
    },
    text: {
      primary: 'var(--color-text-primary)',
      secondary: 'var(--color-text-secondary)',
      tertiary: 'var(--color-text-tertiary)',
      disabled: 'var(--color-text-disabled)',
      inverse: 'var(--color-text-inverse)',
    },
    border: {
      default: 'var(--color-border)',
      divider: 'var(--color-border-divider)',
      focus: 'var(--color-border-focus)',
    },
    semantic: {
      success: { default: 'var(--color-success)', bg: 'var(--color-success-bg)' },
      warning: { default: 'var(--color-warning)', bg: 'var(--color-warning-bg)' },
      error: { default: 'var(--color-error)', bg: 'var(--color-error-bg)' },
      info: { default: 'var(--color-info)', bg: 'var(--color-info-bg)' },
    },
  },
  spacing: {
    '3xs': '0.125rem',
    '2xs': '0.25rem',
    xs: '0.5rem',
    sm: '0.75rem',
    md: '1rem',
    lg: '1.5rem',
    xl: '2rem',
    '2xl': '3rem',
    '3xl': '4rem',
  },
  borderRadius: {
    none: '0',
    sm: '0.25rem',
    md: '0.5rem',
    lg: '1rem',
    xl: '1.5rem',
    '2xl': '2rem',
    full: '9999px',
  },
  shadow: {
    sm: 'var(--shadow-sm)',
    md: 'var(--shadow-md)',
    lg: 'var(--shadow-lg)',
    xl: 'var(--shadow-xl)',
    inner: 'var(--shadow-inner)',
    focus: 'var(--shadow-focus)',
  },
  typography: {
    fontFamily: {
      sans: 'Inter, system-ui, Avenir, Helvetica, Arial, sans-serif',
      mono: 'JetBrains Mono, Fira Code, monospace',
    },
    fontSize: {
      xs: '0.75rem',
      sm: '0.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
      '2xl': '1.5rem',
      '3xl': '1.875rem',
      '4xl': '2.25rem',
    },
    fontWeight: {
      normal: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
    },
  },
  transitions: {
    fast: '150ms cubic-bezier(0.4, 0, 0.2, 1)',
    normal: '300ms cubic-bezier(0.4, 0, 0.2, 1)',
    slow: '500ms cubic-bezier(0.4, 0, 0.2, 1)',
    spring: 'spring(300, 20)',
  },
  breakpoints: {
    sm: '640px',
    md: '768px',
    lg: '1024px',
    xl: '1280px',
  },
  zIndex: {
    base: 0,
    above: 10,
    dropdown: 1000,
    sticky: 1020,
    fixed: 1030,
    modalBackdrop: 1040,
    modal: 1050,
    popover: 1060,
    tooltip: 1070,
  },
  iconSize: {
    sm: '1rem',
    md: '1.25rem',
    lg: '1.5rem',
    xl: '2rem',
  },
  panelSize: {
    sidebarWidth: '24rem',
    timelineHeight: '8rem',
    headerHeight: '3.5rem',
  }
} as const;
