import type { LessonProgram } from '../../types';

export const student_marks: LessonProgram = {
  id: 'student_marks', language: 'python', topic: 'lists', lessonNumber: 6,
  friendlyName: 'Student Marks Management',
  learningObjective: 'Learn to combine iteration, arithmetic and conditionals to process a list of data.',
  lines: [
    { lineNum: 1, tokens: [{ type: 'variable', value: 'marks' }, { type: 'text', value: ' ' }, { type: 'operator', value: '=' }, { type: 'text', value: ' ' }, { type: 'punctuation', value: '[' }, { type: 'number', value: '45' }, { type: 'punctuation', value: ',' }, { type: 'text', value: ' ' }, { type: 'number', value: '80' }, { type: 'punctuation', value: ',' }, { type: 'text', value: ' ' }, { type: 'number', value: '25' }, { type: 'punctuation', value: ',' }, { type: 'text', value: ' ' }, { type: 'number', value: '90' }, { type: 'punctuation', value: ']' }] },
    { lineNum: 2, tokens: [{ type: 'variable', value: 'total' }, { type: 'text', value: ' ' }, { type: 'operator', value: '=' }, { type: 'text', value: ' ' }, { type: 'number', value: '0' }] },
    { lineNum: 3, tokens: [{ type: 'variable', value: 'p_count' }, { type: 'text', value: ' ' }, { type: 'operator', value: '=' }, { type: 'text', value: ' ' }, { type: 'number', value: '0' }] },
    { lineNum: 4, tokens: [{ type: 'variable', value: 'f_count' }, { type: 'text', value: ' ' }, { type: 'operator', value: '=' }, { type: 'text', value: ' ' }, { type: 'number', value: '0' }] },
    { lineNum: 5, tokens: [{ type: 'keyword', value: 'for' }, { type: 'text', value: ' ' }, { type: 'variable', value: 'm' }, { type: 'text', value: ' ' }, { type: 'keyword', value: 'in' }, { type: 'text', value: ' ' }, { type: 'variable', value: 'marks' }, { type: 'punctuation', value: ':' }] },
    { lineNum: 6, tokens: [{ type: 'text', value: '    ' }, { type: 'variable', value: 'total' }, { type: 'text', value: ' ' }, { type: 'operator', value: '+=' }, { type: 'text', value: ' ' }, { type: 'variable', value: 'm' }] },
    { lineNum: 7, tokens: [{ type: 'text', value: '    ' }, { type: 'keyword', value: 'if' }, { type: 'text', value: ' ' }, { type: 'variable', value: 'm' }, { type: 'text', value: ' ' }, { type: 'operator', value: '>=' }, { type: 'text', value: ' ' }, { type: 'number', value: '35' }, { type: 'punctuation', value: ':' }] },
    { lineNum: 8, tokens: [{ type: 'text', value: '        ' }, { type: 'variable', value: 'p_count' }, { type: 'text', value: ' ' }, { type: 'operator', value: '+=' }, { type: 'text', value: ' ' }, { type: 'number', value: '1' }] },
    { lineNum: 9, tokens: [{ type: 'text', value: '    ' }, { type: 'keyword', value: 'else' }, { type: 'punctuation', value: ':' }] },
    { lineNum: 10, tokens: [{ type: 'text', value: '        ' }, { type: 'variable', value: 'f_count' }, { type: 'text', value: ' ' }, { type: 'operator', value: '+=' }, { type: 'text', value: ' ' }, { type: 'number', value: '1' }] },
    { lineNum: 11, tokens: [{ type: 'variable', value: 'avg' }, { type: 'text', value: ' ' }, { type: 'operator', value: '=' }, { type: 'text', value: ' ' }, { type: 'variable', value: 'total' }, { type: 'text', value: ' ' }, { type: 'operator', value: '/' }, { type: 'text', value: ' ' }, { type: 'function', value: 'len' }, { type: 'punctuation', value: '(' }, { type: 'variable', value: 'marks' }, { type: 'punctuation', value: ')' }] },
    { lineNum: 12, tokens: [{ type: 'function', value: 'print' }, { type: 'punctuation', value: '(' }, { type: 'variable', value: 'avg' }, { type: 'punctuation', value: ')' }] },
    { lineNum: 13, tokens: [{ type: 'function', value: 'print' }, { type: 'punctuation', value: '(' }, { type: 'variable', value: 'p_count' }, { type: 'punctuation', value: ')' }] },
  ],
  executionSteps: [
    {
      step: 1, lineNum: 1,
      explanationEnglish: 'Store the exam marks in a list called marks.',
      explanationHinglish: 'Exam marks ko ek list mein store kiya jiska naam marks hai.',
      memorySnapshot: { marks: '"[45, 80, 25, 90]"' },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'marks', value: '"[45, 80, 25, 90]"' },
    },
    {
      step: 2, lineNum: 2,
      explanationEnglish: 'Initialize total to 0.',
      explanationHinglish: 'total ko 0 se shuru kiya.',
      memorySnapshot: { marks: '"[45, 80, 25, 90]"', total: 0 },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'total', value: 0 },
    },
    {
      step: 3, lineNum: 3,
      explanationEnglish: 'Initialize pass count to 0.',
      explanationHinglish: 'Pass count ko 0 se shuru kiya.',
      memorySnapshot: { marks: '"[45, 80, 25, 90]"', total: 0, p_count: 0 },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'p_count', value: 0 },
    },
    {
      step: 4, lineNum: 4,
      explanationEnglish: 'Initialize fail count to 0.',
      explanationHinglish: 'Fail count ko 0 se shuru kiya.',
      memorySnapshot: { marks: '"[45, 80, 25, 90]"', total: 0, p_count: 0, f_count: 0 },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'f_count', value: 0 },
    },
    {
      step: 5, lineNum: 5,
      explanationEnglish: 'Read mark 45 from the list.',
      explanationHinglish: 'List se marks 45 padha.',
      memorySnapshot: { marks: '"[45, 80, 25, 90]"', total: 0, p_count: 0, f_count: 0, m: 45 },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'm', value: 45 },
    },
    {
      step: 6, lineNum: 6,
      explanationEnglish: 'Add 45 to total.',
      explanationHinglish: 'total mein 45 joda.',
      memorySnapshot: { marks: '"[45, 80, 25, 90]"', total: 45, p_count: 0, f_count: 0, m: 45 },
      animationEvent: { type: 'UPDATE_VARIABLE', name: 'total', oldValue: 0, newValue: 45 },
    },
    {
      step: 7, lineNum: 7,
      explanationEnglish: 'Check if marks 45 >= 35 to see if student passed.',
      explanationHinglish: 'Check kiya kya marks 45 >= 35 hai (pass).',
      memorySnapshot: { marks: '"[45, 80, 25, 90]"', total: 45, p_count: 0, f_count: 0, m: 45 },
      animationEvent: { type: 'NONE' },
    },
    {
        step: 8, lineNum: 8,
        explanationEnglish: 'Passed! Increment p_count.',
        explanationHinglish: 'Pass hua! p_count badhaya.',
        memorySnapshot: { marks: '"[45, 80, 25, 90]"', total: 45, p_count: 1, f_count: 0, m: 45 },
        animationEvent: { type: 'UPDATE_VARIABLE', name: 'p_count', oldValue: 0, newValue: 1 },
      },
    {
      step: 9, lineNum: 5,
      explanationEnglish: 'Read mark 80 from the list.',
      explanationHinglish: 'List se marks 80 padha.',
      memorySnapshot: { marks: '"[45, 80, 25, 90]"', total: 45, p_count: 1, f_count: 0, m: 80 },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'm', value: 80 },
    },
    {
      step: 10, lineNum: 6,
      explanationEnglish: 'Add 80 to total.',
      explanationHinglish: 'total mein 80 joda.',
      memorySnapshot: { marks: '"[45, 80, 25, 90]"', total: 125, p_count: 1, f_count: 0, m: 80 },
      animationEvent: { type: 'UPDATE_VARIABLE', name: 'total', oldValue: 45, newValue: 125 },
    },
    {
      step: 11, lineNum: 7,
      explanationEnglish: 'Check if marks 80 >= 35 to see if student passed.',
      explanationHinglish: 'Check kiya kya marks 80 >= 35 hai (pass).',
      memorySnapshot: { marks: '"[45, 80, 25, 90]"', total: 125, p_count: 1, f_count: 0, m: 80 },
      animationEvent: { type: 'NONE' },
    },
    {
        step: 12, lineNum: 8,
        explanationEnglish: 'Passed! Increment p_count.',
        explanationHinglish: 'Pass hua! p_count badhaya.',
        memorySnapshot: { marks: '"[45, 80, 25, 90]"', total: 125, p_count: 2, f_count: 0, m: 80 },
        animationEvent: { type: 'UPDATE_VARIABLE', name: 'p_count', oldValue: 1, newValue: 2 },
      },
    {
      step: 13, lineNum: 5,
      explanationEnglish: 'Read mark 25 from the list.',
      explanationHinglish: 'List se marks 25 padha.',
      memorySnapshot: { marks: '"[45, 80, 25, 90]"', total: 125, p_count: 2, f_count: 0, m: 25 },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'm', value: 25 },
    },
    {
      step: 14, lineNum: 6,
      explanationEnglish: 'Add 25 to total.',
      explanationHinglish: 'total mein 25 joda.',
      memorySnapshot: { marks: '"[45, 80, 25, 90]"', total: 150, p_count: 2, f_count: 0, m: 25 },
      animationEvent: { type: 'UPDATE_VARIABLE', name: 'total', oldValue: 125, newValue: 150 },
    },
    {
      step: 15, lineNum: 7,
      explanationEnglish: 'Check if marks 25 >= 35 to see if student passed.',
      explanationHinglish: 'Check kiya kya marks 25 >= 35 hai (pass).',
      memorySnapshot: { marks: '"[45, 80, 25, 90]"', total: 150, p_count: 2, f_count: 0, m: 25 },
      animationEvent: { type: 'NONE' },
    },
    {
        step: 16, lineNum: 9,
        explanationEnglish: 'Failed. Go to else block.',
        explanationHinglish: 'Fail hua. else block mein gaye.',
        memorySnapshot: { marks: '"[45, 80, 25, 90]"', total: 150, p_count: 2, f_count: 0, m: 25 },
        animationEvent: { type: 'NONE' },
      },
    {
        step: 17, lineNum: 10,
        explanationEnglish: 'Increment f_count.',
        explanationHinglish: 'f_count badhaya.',
        memorySnapshot: { marks: '"[45, 80, 25, 90]"', total: 150, p_count: 2, f_count: 1, m: 25 },
        animationEvent: { type: 'UPDATE_VARIABLE', name: 'f_count', oldValue: 0, newValue: 1 },
      },
    {
      step: 18, lineNum: 5,
      explanationEnglish: 'Read mark 90 from the list.',
      explanationHinglish: 'List se marks 90 padha.',
      memorySnapshot: { marks: '"[45, 80, 25, 90]"', total: 150, p_count: 2, f_count: 1, m: 90 },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'm', value: 90 },
    },
    {
      step: 19, lineNum: 6,
      explanationEnglish: 'Add 90 to total.',
      explanationHinglish: 'total mein 90 joda.',
      memorySnapshot: { marks: '"[45, 80, 25, 90]"', total: 240, p_count: 2, f_count: 1, m: 90 },
      animationEvent: { type: 'UPDATE_VARIABLE', name: 'total', oldValue: 150, newValue: 240 },
    },
    {
      step: 20, lineNum: 7,
      explanationEnglish: 'Check if marks 90 >= 35 to see if student passed.',
      explanationHinglish: 'Check kiya kya marks 90 >= 35 hai (pass).',
      memorySnapshot: { marks: '"[45, 80, 25, 90]"', total: 240, p_count: 2, f_count: 1, m: 90 },
      animationEvent: { type: 'NONE' },
    },
    {
        step: 21, lineNum: 8,
        explanationEnglish: 'Passed! Increment p_count.',
        explanationHinglish: 'Pass hua! p_count badhaya.',
        memorySnapshot: { marks: '"[45, 80, 25, 90]"', total: 240, p_count: 3, f_count: 1, m: 90 },
        animationEvent: { type: 'UPDATE_VARIABLE', name: 'p_count', oldValue: 2, newValue: 3 },
      },
    {
      step: 22, lineNum: 11,
      explanationEnglish: 'Calculate average by dividing total by number of subjects.',
      explanationHinglish: 'total ko subjects ke count se divide karke average nikala.',
      memorySnapshot: { marks: '"[45, 80, 25, 90]"', total: 240, p_count: 3, f_count: 1, m: 90, avg: 60.0 },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'avg', value: 60.0 },
    },
    {
      step: 23, lineNum: 12,
      explanationEnglish: 'Print the average score.',
      explanationHinglish: 'Average score print kiya.',
      memorySnapshot: { marks: '"[45, 80, 25, 90]"', total: 240, p_count: 3, f_count: 1, m: 90, avg: 60.0 },
      consoleOutput: '60.0',
      animationEvent: { type: 'PRINT_VALUE', variableName: 'avg', outputValue: 60.0 },
    },
    {
      step: 24, lineNum: 13,
      explanationEnglish: 'Print the number of subjects passed.',
      explanationHinglish: 'Kitne subjects mein pass hua wo print kiya.',
      memorySnapshot: { marks: '"[45, 80, 25, 90]"', total: 240, p_count: 3, f_count: 1, m: 90, avg: 60.0 },
      consoleOutput: '60.0\n3',
      animationEvent: { type: 'PRINT_VALUE', variableName: 'p_count', outputValue: 3 },
    }
  ],
};