import type { LessonProgram } from '../../types';

export const recursive_factorial: LessonProgram = {
  id: 'recursive_factorial', language: 'python', topic: 'recursion', lessonNumber: 3,
  friendlyName: 'Factorial Using Recursion',
  learningObjective: 'Observe how recursion mathematically builds up a result (n * factorial(n-1)).',
  lines: [
    { lineNum: 1, tokens: [{ type: 'keyword', value: 'def' }, { type: 'text', value: ' ' }, { type: 'function', value: 'factorial' }, { type: 'punctuation', value: '(' }, { type: 'variable', value: 'n' }, { type: 'punctuation', value: ')' }, { type: 'punctuation', value: ':' }] },
    { lineNum: 2, tokens: [{ type: 'text', value: '    ' }, { type: 'keyword', value: 'if' }, { type: 'text', value: ' ' }, { type: 'variable', value: 'n' }, { type: 'text', value: ' ' }, { type: 'operator', value: '<=' }, { type: 'text', value: ' ' }, { type: 'number', value: '1' }, { type: 'punctuation', value: ':' }] },
    { lineNum: 3, tokens: [{ type: 'text', value: '        ' }, { type: 'keyword', value: 'return' }, { type: 'text', value: ' ' }, { type: 'number', value: '1' }] },
    { lineNum: 4, tokens: [{ type: 'text', value: '    ' }, { type: 'variable', value: 'prev_fact' }, { type: 'text', value: ' ' }, { type: 'operator', value: '=' }, { type: 'text', value: ' ' }, { type: 'function', value: 'factorial' }, { type: 'punctuation', value: '(' }, { type: 'variable', value: 'n' }, { type: 'text', value: ' ' }, { type: 'operator', value: '-' }, { type: 'text', value: ' ' }, { type: 'number', value: '1' }, { type: 'punctuation', value: ')' }] },
    { lineNum: 5, tokens: [{ type: 'text', value: '    ' }, { type: 'keyword', value: 'return' }, { type: 'text', value: ' ' }, { type: 'variable', value: 'n' }, { type: 'text', value: ' ' }, { type: 'operator', value: '*' }, { type: 'text', value: ' ' }, { type: 'variable', value: 'prev_fact' }] },
    { lineNum: 6, tokens: [{ type: 'variable', value: 'ans' }, { type: 'text', value: ' ' }, { type: 'operator', value: '=' }, { type: 'text', value: ' ' }, { type: 'function', value: 'factorial' }, { type: 'punctuation', value: '(' }, { type: 'number', value: '3' }, { type: 'punctuation', value: ')' }] },
    { lineNum: 7, tokens: [{ type: 'function', value: 'print' }, { type: 'punctuation', value: '(' }, { type: 'variable', value: 'ans' }, { type: 'punctuation', value: ')' }] },
  ],
  executionSteps: [
    {
      step: 1, lineNum: 1,
      explanationEnglish: 'Define a recursive function to compute factorial.',
      explanationHinglish: 'Factorial calculate karne ke liye recursive function define kiya.',
      memorySnapshot: {},
      animationEvent: { type: 'NONE' },
    },
    {
      step: 2, lineNum: 6,
      explanationEnglish: 'Call factorial(3).',
      explanationHinglish: 'factorial(3) ko call kiya.',
      memorySnapshot: { CallStack: 'factorial(3)' },
      animationEvent: { type: 'NONE' },
    },
    {
      step: 3, lineNum: 1,
      explanationEnglish: 'Entered factorial with n = 3.',
      explanationHinglish: 'factorial function mein n = 3 aya.',
      memorySnapshot: { n: 3, CallStack: 'factorial(3)' },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'n', value: 3 },
    },
    {
      step: 4, lineNum: 2,
      explanationEnglish: 'Check base condition: is n (3) <= 1?',
      explanationHinglish: 'Check kiya kya n (3) <= 1 hai?',
      memorySnapshot: { n: 3, CallStack: 'factorial(3)' },
      animationEvent: { type: 'NONE' },
    },
    {
        step: 5, lineNum: 4,
        explanationEnglish: 'Call factorial(2) recursively. (Push to Stack)',
        explanationHinglish: 'Recursion: factorial(2) ko call kiya. (Stack Push)',
        memorySnapshot: { n: 3, CallStack: 'factorial(3) -> factorial(2)' },
        animationEvent: { type: 'NONE' },
      },
    {
      step: 6, lineNum: 1,
      explanationEnglish: 'Entered factorial with n = 2.',
      explanationHinglish: 'factorial function mein n = 2 aya.',
      memorySnapshot: { n: 2, CallStack: 'factorial(3) -> factorial(2)' },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'n', value: 2 },
    },
    {
      step: 7, lineNum: 2,
      explanationEnglish: 'Check base condition: is n (2) <= 1?',
      explanationHinglish: 'Check kiya kya n (2) <= 1 hai?',
      memorySnapshot: { n: 2, CallStack: 'factorial(3) -> factorial(2)' },
      animationEvent: { type: 'NONE' },
    },
    {
        step: 8, lineNum: 4,
        explanationEnglish: 'Call factorial(1) recursively. (Push to Stack)',
        explanationHinglish: 'Recursion: factorial(1) ko call kiya. (Stack Push)',
        memorySnapshot: { n: 2, CallStack: 'factorial(3) -> factorial(2) -> factorial(1)' },
        animationEvent: { type: 'NONE' },
      },
    {
      step: 9, lineNum: 1,
      explanationEnglish: 'Entered factorial with n = 1.',
      explanationHinglish: 'factorial function mein n = 1 aya.',
      memorySnapshot: { n: 1, CallStack: 'factorial(3) -> factorial(2) -> factorial(1)' },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'n', value: 1 },
    },
    {
      step: 10, lineNum: 2,
      explanationEnglish: 'Check base condition: is n (1) <= 1?',
      explanationHinglish: 'Check kiya kya n (1) <= 1 hai?',
      memorySnapshot: { n: 1, CallStack: 'factorial(3) -> factorial(2) -> factorial(1)' },
      animationEvent: { type: 'NONE' },
    },
    {
        step: 11, lineNum: 3,
        explanationEnglish: 'Base condition met! Return 1.',
        explanationHinglish: 'Base condition true! 1 return kiya.',
        memorySnapshot: { n: 1, CallStack: 'factorial(3) -> factorial(2) -> factorial(1)' },
        animationEvent: { type: 'COMPUTE', inputs: [], operator: 'return', result: 1, storeIn: 'ReturnValue' },
      },
    {
        step: 12, lineNum: 4,
        explanationEnglish: 'Returned from factorial(1) with value 1. (Pop from Stack)',
        explanationHinglish: 'factorial(1) se 1 return aaya. (Stack Pop)',
        memorySnapshot: { n: 2, CallStack: 'factorial(3) -> factorial(2)' },
        animationEvent: { type: 'NONE' },
      },
    {
        step: 13, lineNum: 5,
        explanationEnglish: 'Compute 2 * 1 = 2 and return it.',
        explanationHinglish: '2 aur 1 ko multiply karke 2 return kiya.',
        memorySnapshot: { n: 2, CallStack: 'factorial(3) -> factorial(2)' },
        animationEvent: { type: 'COMPUTE', inputs: ['n', 'ReturnValue'], operator: '*', result: 2, storeIn: 'ReturnValue' },
      },
    {
        step: 14, lineNum: 4,
        explanationEnglish: 'Returned from factorial(2) with value 2. (Pop from Stack)',
        explanationHinglish: 'factorial(2) se 2 return aaya. (Stack Pop)',
        memorySnapshot: { n: 3, CallStack: 'factorial(3)' },
        animationEvent: { type: 'NONE' },
      },
    {
        step: 15, lineNum: 5,
        explanationEnglish: 'Compute 3 * 2 = 6 and return it.',
        explanationHinglish: '3 aur 2 ko multiply karke 6 return kiya.',
        memorySnapshot: { n: 3, CallStack: 'factorial(3)' },
        animationEvent: { type: 'COMPUTE', inputs: ['n', 'ReturnValue'], operator: '*', result: 6, storeIn: 'ReturnValue' },
      },
    {
      step: 16, lineNum: 6,
      explanationEnglish: 'Store the final result (6) in "ans".',
      explanationHinglish: 'Final result (6) ko "ans" mein store kiya.',
      memorySnapshot: { ans: 6 },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'ans', value: 6 },
    },
    {
      step: 17, lineNum: 7,
      explanationEnglish: 'Print the factorial.',
      explanationHinglish: 'Factorial print kiya.',
      memorySnapshot: { ans: 6 },
      consoleOutput: '6',
      animationEvent: { type: 'PRINT_VALUE', variableName: 'ans', outputValue: 6 },
    }
  ],
};