import type { LessonProgram } from '../../types';

export const recursive_sum: LessonProgram = {
  id: 'recursive_sum', language: 'python', topic: 'recursion', lessonNumber: 2,
  friendlyName: 'Sum of N Natural Numbers',
  learningObjective: 'Understand how a recursive function computes values and bubbles them up the call stack.',
  lines: [
    { lineNum: 1, tokens: [{ type: 'keyword', value: 'def' }, { type: 'text', value: ' ' }, { type: 'function', value: 'sum_n' }, { type: 'punctuation', value: '(' }, { type: 'variable', value: 'n' }, { type: 'punctuation', value: ')' }, { type: 'punctuation', value: ':' }] },
    { lineNum: 2, tokens: [{ type: 'text', value: '    ' }, { type: 'keyword', value: 'if' }, { type: 'text', value: ' ' }, { type: 'variable', value: 'n' }, { type: 'text', value: ' ' }, { type: 'operator', value: '<=' }, { type: 'text', value: ' ' }, { type: 'number', value: '1' }, { type: 'punctuation', value: ':' }] },
    { lineNum: 3, tokens: [{ type: 'text', value: '        ' }, { type: 'keyword', value: 'return' }, { type: 'text', value: ' ' }, { type: 'number', value: '1' }] },
    { lineNum: 4, tokens: [{ type: 'text', value: '    ' }, { type: 'variable', value: 'prev_sum' }, { type: 'text', value: ' ' }, { type: 'operator', value: '=' }, { type: 'text', value: ' ' }, { type: 'function', value: 'sum_n' }, { type: 'punctuation', value: '(' }, { type: 'variable', value: 'n' }, { type: 'text', value: ' ' }, { type: 'operator', value: '-' }, { type: 'text', value: ' ' }, { type: 'number', value: '1' }, { type: 'punctuation', value: ')' }] },
    { lineNum: 5, tokens: [{ type: 'text', value: '    ' }, { type: 'keyword', value: 'return' }, { type: 'text', value: ' ' }, { type: 'variable', value: 'n' }, { type: 'text', value: ' ' }, { type: 'operator', value: '+' }, { type: 'text', value: ' ' }, { type: 'variable', value: 'prev_sum' }] },
    { lineNum: 6, tokens: [{ type: 'variable', value: 'ans' }, { type: 'text', value: ' ' }, { type: 'operator', value: '=' }, { type: 'text', value: ' ' }, { type: 'function', value: 'sum_n' }, { type: 'punctuation', value: '(' }, { type: 'number', value: '3' }, { type: 'punctuation', value: ')' }] },
    { lineNum: 7, tokens: [{ type: 'function', value: 'print' }, { type: 'punctuation', value: '(' }, { type: 'variable', value: 'ans' }, { type: 'punctuation', value: ')' }] },
  ],
  executionSteps: [
    {
      step: 1, lineNum: 1,
      explanationEnglish: 'Define a recursive function to compute the sum of N natural numbers.',
      explanationHinglish: 'N natural numbers ka sum nikalne ke liye recursive function banaya.',
      memorySnapshot: {},
      animationEvent: { type: 'NONE' },
    },
    {
      step: 2, lineNum: 6,
      explanationEnglish: 'Call sum_n(3).',
      explanationHinglish: 'sum_n(3) ko call kiya.',
      memorySnapshot: { CallStack: 'sum_n(3)' },
      animationEvent: { type: 'NONE' },
    },
    {
      step: 3, lineNum: 1,
      explanationEnglish: 'Entered sum_n with n = 3.',
      explanationHinglish: 'sum_n function mein n = 3 ke sath enter kiya.',
      memorySnapshot: { n: 3, CallStack: 'sum_n(3)' },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'n', value: 3 },
    },
    {
      step: 4, lineNum: 2,
      explanationEnglish: 'Check base condition: is n (3) <= 1?',
      explanationHinglish: 'Check kiya kya n (3) <= 1 hai?',
      memorySnapshot: { n: 3, CallStack: 'sum_n(3)' },
      animationEvent: { type: 'NONE' },
    },
    {
        step: 5, lineNum: 4,
        explanationEnglish: 'Call sum_n(2) recursively. (Push to Stack)',
        explanationHinglish: 'Recursion: sum_n(2) ko call kiya. (Stack Push)',
        memorySnapshot: { n: 3, CallStack: 'sum_n(3) -> sum_n(2)' },
        animationEvent: { type: 'NONE' },
      },
    {
      step: 6, lineNum: 1,
      explanationEnglish: 'Entered sum_n with n = 2.',
      explanationHinglish: 'sum_n function mein n = 2 ke sath enter kiya.',
      memorySnapshot: { n: 2, CallStack: 'sum_n(3) -> sum_n(2)' },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'n', value: 2 },
    },
    {
      step: 7, lineNum: 2,
      explanationEnglish: 'Check base condition: is n (2) <= 1?',
      explanationHinglish: 'Check kiya kya n (2) <= 1 hai?',
      memorySnapshot: { n: 2, CallStack: 'sum_n(3) -> sum_n(2)' },
      animationEvent: { type: 'NONE' },
    },
    {
        step: 8, lineNum: 4,
        explanationEnglish: 'Call sum_n(1) recursively. (Push to Stack)',
        explanationHinglish: 'Recursion: sum_n(1) ko call kiya. (Stack Push)',
        memorySnapshot: { n: 2, CallStack: 'sum_n(3) -> sum_n(2) -> sum_n(1)' },
        animationEvent: { type: 'NONE' },
      },
    {
      step: 9, lineNum: 1,
      explanationEnglish: 'Entered sum_n with n = 1.',
      explanationHinglish: 'sum_n function mein n = 1 ke sath enter kiya.',
      memorySnapshot: { n: 1, CallStack: 'sum_n(3) -> sum_n(2) -> sum_n(1)' },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'n', value: 1 },
    },
    {
      step: 10, lineNum: 2,
      explanationEnglish: 'Check base condition: is n (1) <= 1?',
      explanationHinglish: 'Check kiya kya n (1) <= 1 hai?',
      memorySnapshot: { n: 1, CallStack: 'sum_n(3) -> sum_n(2) -> sum_n(1)' },
      animationEvent: { type: 'NONE' },
    },
    {
        step: 11, lineNum: 3,
        explanationEnglish: 'Base condition met! Return 1.',
        explanationHinglish: 'Base condition true! 1 return kiya.',
        memorySnapshot: { n: 1, CallStack: 'sum_n(3) -> sum_n(2) -> sum_n(1)' },
        animationEvent: { type: 'COMPUTE', inputs: [], operator: 'return', result: 1, storeIn: 'ReturnValue' },
      },
    {
        step: 12, lineNum: 4,
        explanationEnglish: 'Returned from sum_n(1) with value 1. (Pop from Stack)',
        explanationHinglish: 'sum_n(1) se 1 return aaya. (Stack Pop)',
        memorySnapshot: { n: 2, CallStack: 'sum_n(3) -> sum_n(2)' },
        animationEvent: { type: 'NONE' },
      },
    {
        step: 13, lineNum: 5,
        explanationEnglish: 'Compute 2 + 1 = 3 and return it.',
        explanationHinglish: '2 aur 1 ko add karke 3 return kiya.',
        memorySnapshot: { n: 2, CallStack: 'sum_n(3) -> sum_n(2)' },
        animationEvent: { type: 'COMPUTE', inputs: ['n', 'ReturnValue'], operator: '+', result: 3, storeIn: 'ReturnValue' },
      },
    {
        step: 14, lineNum: 4,
        explanationEnglish: 'Returned from sum_n(2) with value 3. (Pop from Stack)',
        explanationHinglish: 'sum_n(2) se 3 return aaya. (Stack Pop)',
        memorySnapshot: { n: 3, CallStack: 'sum_n(3)' },
        animationEvent: { type: 'NONE' },
      },
    {
        step: 15, lineNum: 5,
        explanationEnglish: 'Compute 3 + 3 = 6 and return it.',
        explanationHinglish: '3 aur 3 ko add karke 6 return kiya.',
        memorySnapshot: { n: 3, CallStack: 'sum_n(3)' },
        animationEvent: { type: 'COMPUTE', inputs: ['n', 'ReturnValue'], operator: '+', result: 6, storeIn: 'ReturnValue' },
      },
    {
      step: 16, lineNum: 6,
      explanationEnglish: 'Store the final sum (6) in "ans".',
      explanationHinglish: 'Final sum (6) ko "ans" mein store kiya.',
      memorySnapshot: { ans: 6 },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'ans', value: 6 },
    },
    {
      step: 17, lineNum: 7,
      explanationEnglish: 'Print the final answer.',
      explanationHinglish: 'Answer print kiya.',
      memorySnapshot: { ans: 6 },
      consoleOutput: '6',
      animationEvent: { type: 'PRINT_VALUE', variableName: 'ans', outputValue: 6 },
    }
  ],
};