import type { LessonProgram } from '../../types';

export const recursive_fibonacci: LessonProgram = {
  id: 'recursive_fibonacci', language: 'python', topic: 'recursion', lessonNumber: 4,
  friendlyName: 'Fibonacci Series Using Recursion',
  learningObjective: 'Understand how a function can branch out into multiple recursive calls.',
  lines: [
    { lineNum: 1, tokens: [{ type: 'keyword', value: 'def' }, { type: 'text', value: ' ' }, { type: 'function', value: 'fib' }, { type: 'punctuation', value: '(' }, { type: 'variable', value: 'n' }, { type: 'punctuation', value: ')' }, { type: 'punctuation', value: ':' }] },
    { lineNum: 2, tokens: [{ type: 'text', value: '    ' }, { type: 'keyword', value: 'if' }, { type: 'text', value: ' ' }, { type: 'variable', value: 'n' }, { type: 'text', value: ' ' }, { type: 'operator', value: '<=' }, { type: 'text', value: ' ' }, { type: 'number', value: '1' }, { type: 'punctuation', value: ':' }] },
    { lineNum: 3, tokens: [{ type: 'text', value: '        ' }, { type: 'keyword', value: 'return' }, { type: 'text', value: ' ' }, { type: 'variable', value: 'n' }] },
    { lineNum: 4, tokens: [{ type: 'text', value: '    ' }, { type: 'variable', value: 'left_val' }, { type: 'text', value: ' ' }, { type: 'operator', value: '=' }, { type: 'text', value: ' ' }, { type: 'function', value: 'fib' }, { type: 'punctuation', value: '(' }, { type: 'variable', value: 'n' }, { type: 'text', value: ' ' }, { type: 'operator', value: '-' }, { type: 'text', value: ' ' }, { type: 'number', value: '1' }, { type: 'punctuation', value: ')' }] },
    { lineNum: 5, tokens: [{ type: 'text', value: '    ' }, { type: 'variable', value: 'right_val' }, { type: 'text', value: ' ' }, { type: 'operator', value: '=' }, { type: 'text', value: ' ' }, { type: 'function', value: 'fib' }, { type: 'punctuation', value: '(' }, { type: 'variable', value: 'n' }, { type: 'text', value: ' ' }, { type: 'operator', value: '-' }, { type: 'text', value: ' ' }, { type: 'number', value: '2' }, { type: 'punctuation', value: ')' }] },
    { lineNum: 6, tokens: [{ type: 'text', value: '    ' }, { type: 'keyword', value: 'return' }, { type: 'text', value: ' ' }, { type: 'variable', value: 'left_val' }, { type: 'text', value: ' ' }, { type: 'operator', value: '+' }, { type: 'text', value: ' ' }, { type: 'variable', value: 'right_val' }] },
    { lineNum: 7, tokens: [{ type: 'variable', value: 'ans' }, { type: 'text', value: ' ' }, { type: 'operator', value: '=' }, { type: 'text', value: ' ' }, { type: 'function', value: 'fib' }, { type: 'punctuation', value: '(' }, { type: 'number', value: '3' }, { type: 'punctuation', value: ')' }] },
    { lineNum: 8, tokens: [{ type: 'function', value: 'print' }, { type: 'punctuation', value: '(' }, { type: 'variable', value: 'ans' }, { type: 'punctuation', value: ')' }] },
  ],
  executionSteps: [
    {
      step: 1, lineNum: 1,
      explanationEnglish: 'Define a recursive function to compute the nth Fibonacci number.',
      explanationHinglish: 'Fibonacci series ka nth number nikalne ke liye function define kiya.',
      memorySnapshot: {},
      animationEvent: { type: 'NONE' },
    },
    {
      step: 2, lineNum: 7,
      explanationEnglish: 'Call fib(3).',
      explanationHinglish: 'fib(3) ko call kiya.',
      memorySnapshot: { CallStack: 'fib(3)' },
      animationEvent: { type: 'NONE' },
    },
    {
      step: 3, lineNum: 1,
      explanationEnglish: 'Entered fib with n = 3.',
      explanationHinglish: 'fib function mein n = 3 aya.',
      memorySnapshot: { n: 3, CallStack: 'fib(3)' },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'n', value: 3 },
    },
    {
      step: 4, lineNum: 2,
      explanationEnglish: 'Check base condition: is n (3) <= 1?',
      explanationHinglish: 'Check kiya kya n (3) <= 1 hai?',
      memorySnapshot: { n: 3, CallStack: 'fib(3)' },
      animationEvent: { type: 'NONE' },
    },
    {
        step: 5, lineNum: 4,
        explanationEnglish: 'Call fib(2) recursively. (Left Branch Push)',
        explanationHinglish: 'Left branch ke liye fib(2) ko call kiya. (Stack Push)',
        memorySnapshot: { n: 3, CallStack: 'fib(3) -> fib(2)' },
        animationEvent: { type: 'NONE' },
      },
    {
      step: 6, lineNum: 1,
      explanationEnglish: 'Entered fib with n = 2.',
      explanationHinglish: 'fib function mein n = 2 aya.',
      memorySnapshot: { n: 2, CallStack: 'fib(3) -> fib(2)' },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'n', value: 2 },
    },
    {
      step: 7, lineNum: 2,
      explanationEnglish: 'Check base condition: is n (2) <= 1?',
      explanationHinglish: 'Check kiya kya n (2) <= 1 hai?',
      memorySnapshot: { n: 2, CallStack: 'fib(3) -> fib(2)' },
      animationEvent: { type: 'NONE' },
    },
    {
        step: 8, lineNum: 4,
        explanationEnglish: 'Call fib(1) recursively. (Left Branch Push)',
        explanationHinglish: 'Left branch ke liye fib(1) ko call kiya. (Stack Push)',
        memorySnapshot: { n: 2, CallStack: 'fib(3) -> fib(2) -> fib(1)' },
        animationEvent: { type: 'NONE' },
      },
    {
      step: 9, lineNum: 1,
      explanationEnglish: 'Entered fib with n = 1.',
      explanationHinglish: 'fib function mein n = 1 aya.',
      memorySnapshot: { n: 1, CallStack: 'fib(3) -> fib(2) -> fib(1)' },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'n', value: 1 },
    },
    {
      step: 10, lineNum: 2,
      explanationEnglish: 'Check base condition: is n (1) <= 1?',
      explanationHinglish: 'Check kiya kya n (1) <= 1 hai?',
      memorySnapshot: { n: 1, CallStack: 'fib(3) -> fib(2) -> fib(1)' },
      animationEvent: { type: 'NONE' },
    },
    {
        step: 11, lineNum: 3,
        explanationEnglish: 'Base condition met! Return 1.',
        explanationHinglish: 'Base condition true! 1 return kiya.',
        memorySnapshot: { n: 1, CallStack: 'fib(3) -> fib(2) -> fib(1)' },
        animationEvent: { type: 'COMPUTE', inputs: [], operator: 'return', result: 1, storeIn: 'ReturnValue' },
      },
    {
        step: 12, lineNum: 4,
        explanationEnglish: 'Returned from fib(1) with value 1.',
        explanationHinglish: 'fib(1) se 1 wapas aaya.',
        memorySnapshot: { n: 2, left_val: 1, CallStack: 'fib(3) -> fib(2)' },
        animationEvent: { type: 'CREATE_VARIABLE', name: 'left_val', value: 1 },
      },
    {
        step: 13, lineNum: 5,
        explanationEnglish: 'Call fib(0) recursively. (Right Branch Push)',
        explanationHinglish: 'Right branch ke liye fib(0) ko call kiya. (Stack Push)',
        memorySnapshot: { n: 2, left_val: 1, CallStack: 'fib(3) -> fib(2) -> fib(0)' },
        animationEvent: { type: 'NONE' },
      },
    {
      step: 14, lineNum: 1,
      explanationEnglish: 'Entered fib with n = 0.',
      explanationHinglish: 'fib function mein n = 0 aya.',
      memorySnapshot: { n: 0, CallStack: 'fib(3) -> fib(2) -> fib(0)' },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'n', value: 0 },
    },
    {
      step: 15, lineNum: 2,
      explanationEnglish: 'Check base condition: is n (0) <= 1?',
      explanationHinglish: 'Check kiya kya n (0) <= 1 hai?',
      memorySnapshot: { n: 0, CallStack: 'fib(3) -> fib(2) -> fib(0)' },
      animationEvent: { type: 'NONE' },
    },
    {
        step: 16, lineNum: 3,
        explanationEnglish: 'Base condition met! Return 0.',
        explanationHinglish: 'Base condition true! 0 return kiya.',
        memorySnapshot: { n: 0, CallStack: 'fib(3) -> fib(2) -> fib(0)' },
        animationEvent: { type: 'COMPUTE', inputs: [], operator: 'return', result: 0, storeIn: 'ReturnValue' },
      },
    {
        step: 17, lineNum: 5,
        explanationEnglish: 'Returned from fib(0) with value 0.',
        explanationHinglish: 'fib(0) se 0 wapas aaya.',
        memorySnapshot: { n: 2, left_val: 1, right_val: 0, CallStack: 'fib(3) -> fib(2)' },
        animationEvent: { type: 'CREATE_VARIABLE', name: 'right_val', value: 0 },
      },
    {
        step: 18, lineNum: 6,
        explanationEnglish: 'Compute 1 + 0 = 1 and return it.',
        explanationHinglish: '1 aur 0 ko add karke 1 return kiya.',
        memorySnapshot: { n: 2, left_val: 1, right_val: 0, CallStack: 'fib(3) -> fib(2)' },
        animationEvent: { type: 'COMPUTE', inputs: ['left_val', 'right_val'], operator: '+', result: 1, storeIn: 'ReturnValue' },
      },
    {
        step: 19, lineNum: 4,
        explanationEnglish: 'Returned from fib(2) with value 1.',
        explanationHinglish: 'fib(2) se 1 wapas aaya.',
        memorySnapshot: { n: 3, left_val: 1, CallStack: 'fib(3)' },
        animationEvent: { type: 'CREATE_VARIABLE', name: 'left_val', value: 1 },
      },
    {
        step: 20, lineNum: 5,
        explanationEnglish: 'Call fib(1) recursively. (Right Branch Push)',
        explanationHinglish: 'Right branch ke liye fib(1) ko call kiya. (Stack Push)',
        memorySnapshot: { n: 3, left_val: 1, CallStack: 'fib(3) -> fib(1)' },
        animationEvent: { type: 'NONE' },
      },
    {
      step: 21, lineNum: 1,
      explanationEnglish: 'Entered fib with n = 1.',
      explanationHinglish: 'fib function mein n = 1 aya.',
      memorySnapshot: { n: 1, CallStack: 'fib(3) -> fib(1)' },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'n', value: 1 },
    },
    {
      step: 22, lineNum: 2,
      explanationEnglish: 'Check base condition: is n (1) <= 1?',
      explanationHinglish: 'Check kiya kya n (1) <= 1 hai?',
      memorySnapshot: { n: 1, CallStack: 'fib(3) -> fib(1)' },
      animationEvent: { type: 'NONE' },
    },
    {
        step: 23, lineNum: 3,
        explanationEnglish: 'Base condition met! Return 1.',
        explanationHinglish: 'Base condition true! 1 return kiya.',
        memorySnapshot: { n: 1, CallStack: 'fib(3) -> fib(1)' },
        animationEvent: { type: 'COMPUTE', inputs: [], operator: 'return', result: 1, storeIn: 'ReturnValue' },
      },
    {
        step: 24, lineNum: 5,
        explanationEnglish: 'Returned from fib(1) with value 1.',
        explanationHinglish: 'fib(1) se 1 wapas aaya.',
        memorySnapshot: { n: 3, left_val: 1, right_val: 1, CallStack: 'fib(3)' },
        animationEvent: { type: 'CREATE_VARIABLE', name: 'right_val', value: 1 },
      },
    {
        step: 25, lineNum: 6,
        explanationEnglish: 'Compute 1 + 1 = 2 and return it.',
        explanationHinglish: '1 aur 1 ko add karke 2 return kiya.',
        memorySnapshot: { n: 3, left_val: 1, right_val: 1, CallStack: 'fib(3)' },
        animationEvent: { type: 'COMPUTE', inputs: ['left_val', 'right_val'], operator: '+', result: 2, storeIn: 'ReturnValue' },
      },
    {
      step: 26, lineNum: 7,
      explanationEnglish: 'Store the final result in "ans".',
      explanationHinglish: 'Final result "ans" mein store kiya.',
      memorySnapshot: { ans: 2 },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'ans', value: 2 },
    },
    {
      step: 27, lineNum: 8,
      explanationEnglish: 'Print the 3rd Fibonacci number.',
      explanationHinglish: '3rd Fibonacci number print kiya.',
      memorySnapshot: { ans: 2 },
      consoleOutput: '2',
      animationEvent: { type: 'PRINT_VALUE', variableName: 'ans', outputValue: 2 },
    }
  ],
};