import type { LessonProgram } from '../../types';

export const recursive_power: LessonProgram = {
  id: 'recursive_power', language: 'python', topic: 'recursion', lessonNumber: 5,
  friendlyName: 'Power of a Number Using Recursion',
  learningObjective: 'Observe how recursion performs repeated multiplication to compute exponents.',
  lines: [
    { lineNum: 1, tokens: [{ type: 'keyword', value: 'def' }, { type: 'text', value: ' ' }, { type: 'function', value: 'power' }, { type: 'punctuation', value: '(' }, { type: 'variable', value: 'base' }, { type: 'punctuation', value: ',' }, { type: 'text', value: ' ' }, { type: 'variable', value: 'exp' }, { type: 'punctuation', value: ')' }, { type: 'punctuation', value: ':' }] },
    { lineNum: 2, tokens: [{ type: 'text', value: '    ' }, { type: 'keyword', value: 'if' }, { type: 'text', value: ' ' }, { type: 'variable', value: 'exp' }, { type: 'text', value: ' ' }, { type: 'operator', value: '==' }, { type: 'text', value: ' ' }, { type: 'number', value: '0' }, { type: 'punctuation', value: ':' }] },
    { lineNum: 3, tokens: [{ type: 'text', value: '        ' }, { type: 'keyword', value: 'return' }, { type: 'text', value: ' ' }, { type: 'number', value: '1' }] },
    { lineNum: 4, tokens: [{ type: 'text', value: '    ' }, { type: 'variable', value: 'prev_pow' }, { type: 'text', value: ' ' }, { type: 'operator', value: '=' }, { type: 'text', value: ' ' }, { type: 'function', value: 'power' }, { type: 'punctuation', value: '(' }, { type: 'variable', value: 'base' }, { type: 'punctuation', value: ',' }, { type: 'text', value: ' ' }, { type: 'variable', value: 'exp' }, { type: 'text', value: ' ' }, { type: 'operator', value: '-' }, { type: 'text', value: ' ' }, { type: 'number', value: '1' }, { type: 'punctuation', value: ')' }] },
    { lineNum: 5, tokens: [{ type: 'text', value: '    ' }, { type: 'keyword', value: 'return' }, { type: 'text', value: ' ' }, { type: 'variable', value: 'base' }, { type: 'text', value: ' ' }, { type: 'operator', value: '*' }, { type: 'text', value: ' ' }, { type: 'variable', value: 'prev_pow' }] },
    { lineNum: 6, tokens: [{ type: 'variable', value: 'ans' }, { type: 'text', value: ' ' }, { type: 'operator', value: '=' }, { type: 'text', value: ' ' }, { type: 'function', value: 'power' }, { type: 'punctuation', value: '(' }, { type: 'number', value: '2' }, { type: 'punctuation', value: ',' }, { type: 'text', value: ' ' }, { type: 'number', value: '3' }, { type: 'punctuation', value: ')' }] },
    { lineNum: 7, tokens: [{ type: 'function', value: 'print' }, { type: 'punctuation', value: '(' }, { type: 'variable', value: 'ans' }, { type: 'punctuation', value: ')' }] },
  ],
  executionSteps: [
    {
      step: 1, lineNum: 1,
      explanationEnglish: 'Define a recursive function to compute the power of a number.',
      explanationHinglish: 'Number ka power calculate karne ke liye recursive function banaya.',
      memorySnapshot: {},
      animationEvent: { type: 'NONE' },
    },
    {
      step: 2, lineNum: 6,
      explanationEnglish: 'Call power(2, 3) to compute 2 to the power of 3.',
      explanationHinglish: '2 ki power 3 nikalne ke liye power(2, 3) ko call kiya.',
      memorySnapshot: { CallStack: 'power(2, 3)' },
      animationEvent: { type: 'NONE' },
    },
    {
      step: 3, lineNum: 1,
      explanationEnglish: 'Entered power with base = 2, exp = 3.',
      explanationHinglish: 'power function mein base = 2, exp = 3 aya.',
      memorySnapshot: { base: 2, exp: 3, CallStack: 'power(2, 3)' },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'exp', value: 3 },
    },
    {
      step: 4, lineNum: 2,
      explanationEnglish: 'Check base condition: is exp (3) == 0?',
      explanationHinglish: 'Check kiya kya exp (3) == 0 hai?',
      memorySnapshot: { base: 2, exp: 3, CallStack: 'power(2, 3)' },
      animationEvent: { type: 'NONE' },
    },
    {
        step: 5, lineNum: 4,
        explanationEnglish: 'Call power(2, 2) recursively. (Push to Stack)',
        explanationHinglish: 'Recursion: power(2, 2) ko call kiya. (Stack Push)',
        memorySnapshot: { base: 2, exp: 3, CallStack: 'power(2, 3) -> power(2, 2)' },
        animationEvent: { type: 'NONE' },
      },
    {
      step: 6, lineNum: 1,
      explanationEnglish: 'Entered power with base = 2, exp = 2.',
      explanationHinglish: 'power function mein base = 2, exp = 2 aya.',
      memorySnapshot: { base: 2, exp: 2, CallStack: 'power(2, 3) -> power(2, 2)' },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'exp', value: 2 },
    },
    {
      step: 7, lineNum: 2,
      explanationEnglish: 'Check base condition: is exp (2) == 0?',
      explanationHinglish: 'Check kiya kya exp (2) == 0 hai?',
      memorySnapshot: { base: 2, exp: 2, CallStack: 'power(2, 3) -> power(2, 2)' },
      animationEvent: { type: 'NONE' },
    },
    {
        step: 8, lineNum: 4,
        explanationEnglish: 'Call power(2, 1) recursively. (Push to Stack)',
        explanationHinglish: 'Recursion: power(2, 1) ko call kiya. (Stack Push)',
        memorySnapshot: { base: 2, exp: 2, CallStack: 'power(2, 3) -> power(2, 2) -> power(2, 1)' },
        animationEvent: { type: 'NONE' },
      },
    {
      step: 9, lineNum: 1,
      explanationEnglish: 'Entered power with base = 2, exp = 1.',
      explanationHinglish: 'power function mein base = 2, exp = 1 aya.',
      memorySnapshot: { base: 2, exp: 1, CallStack: 'power(2, 3) -> power(2, 2) -> power(2, 1)' },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'exp', value: 1 },
    },
    {
      step: 10, lineNum: 2,
      explanationEnglish: 'Check base condition: is exp (1) == 0?',
      explanationHinglish: 'Check kiya kya exp (1) == 0 hai?',
      memorySnapshot: { base: 2, exp: 1, CallStack: 'power(2, 3) -> power(2, 2) -> power(2, 1)' },
      animationEvent: { type: 'NONE' },
    },
    {
        step: 11, lineNum: 4,
        explanationEnglish: 'Call power(2, 0) recursively. (Push to Stack)',
        explanationHinglish: 'Recursion: power(2, 0) ko call kiya. (Stack Push)',
        memorySnapshot: { base: 2, exp: 1, CallStack: 'power(2, 3) -> power(2, 2) -> power(2, 1) -> power(2, 0)' },
        animationEvent: { type: 'NONE' },
      },
    {
      step: 12, lineNum: 1,
      explanationEnglish: 'Entered power with base = 2, exp = 0.',
      explanationHinglish: 'power function mein base = 2, exp = 0 aya.',
      memorySnapshot: { base: 2, exp: 0, CallStack: 'power(2, 3) -> power(2, 2) -> power(2, 1) -> power(2, 0)' },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'exp', value: 0 },
    },
    {
      step: 13, lineNum: 2,
      explanationEnglish: 'Check base condition: is exp (0) == 0?',
      explanationHinglish: 'Check kiya kya exp (0) == 0 hai?',
      memorySnapshot: { base: 2, exp: 0, CallStack: 'power(2, 3) -> power(2, 2) -> power(2, 1) -> power(2, 0)' },
      animationEvent: { type: 'NONE' },
    },
    {
        step: 14, lineNum: 3,
        explanationEnglish: 'Base condition met! Anything to power 0 is 1. Return 1.',
        explanationHinglish: 'Base condition true! Power 0 ka matlab 1 hota hai. 1 return kiya.',
        memorySnapshot: { base: 2, exp: 0, CallStack: 'power(2, 3) -> power(2, 2) -> power(2, 1) -> power(2, 0)' },
        animationEvent: { type: 'COMPUTE', inputs: [], operator: 'return', result: 1, storeIn: 'ReturnValue' },
      },
    {
        step: 15, lineNum: 4,
        explanationEnglish: 'Returned from power(2, 0) with value 1. (Pop from Stack)',
        explanationHinglish: 'power(2, 0) se 1 return aaya.',
        memorySnapshot: { base: 2, exp: 1, CallStack: 'power(2, 3) -> power(2, 2) -> power(2, 1)' },
        animationEvent: { type: 'NONE' },
      },
    {
        step: 16, lineNum: 5,
        explanationEnglish: 'Compute 2 * 1 = 2 and return it.',
        explanationHinglish: '2 aur 1 ko multiply karke 2 return kiya.',
        memorySnapshot: { base: 2, exp: 1, CallStack: 'power(2, 3) -> power(2, 2) -> power(2, 1)' },
        animationEvent: { type: 'COMPUTE', inputs: ['base', 'ReturnValue'], operator: '*', result: 2, storeIn: 'ReturnValue' },
      },
    {
        step: 17, lineNum: 4,
        explanationEnglish: 'Returned from power(2, 1) with value 2. (Pop from Stack)',
        explanationHinglish: 'power(2, 1) se 2 return aaya.',
        memorySnapshot: { base: 2, exp: 2, CallStack: 'power(2, 3) -> power(2, 2)' },
        animationEvent: { type: 'NONE' },
      },
    {
        step: 18, lineNum: 5,
        explanationEnglish: 'Compute 2 * 2 = 4 and return it.',
        explanationHinglish: '2 aur 2 ko multiply karke 4 return kiya.',
        memorySnapshot: { base: 2, exp: 2, CallStack: 'power(2, 3) -> power(2, 2)' },
        animationEvent: { type: 'COMPUTE', inputs: ['base', 'ReturnValue'], operator: '*', result: 4, storeIn: 'ReturnValue' },
      },
    {
        step: 19, lineNum: 4,
        explanationEnglish: 'Returned from power(2, 2) with value 4. (Pop from Stack)',
        explanationHinglish: 'power(2, 2) se 4 return aaya.',
        memorySnapshot: { base: 2, exp: 3, CallStack: 'power(2, 3)' },
        animationEvent: { type: 'NONE' },
      },
    {
        step: 20, lineNum: 5,
        explanationEnglish: 'Compute 2 * 4 = 8 and return it.',
        explanationHinglish: '2 aur 4 ko multiply karke 8 return kiya.',
        memorySnapshot: { base: 2, exp: 3, CallStack: 'power(2, 3)' },
        animationEvent: { type: 'COMPUTE', inputs: ['base', 'ReturnValue'], operator: '*', result: 8, storeIn: 'ReturnValue' },
      },
    {
      step: 21, lineNum: 6,
      explanationEnglish: 'Store the final result (8) in "ans".',
      explanationHinglish: 'Final result (8) ko "ans" mein store kiya.',
      memorySnapshot: { ans: 8 },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'ans', value: 8 },
    },
    {
      step: 22, lineNum: 7,
      explanationEnglish: 'Print the computed power.',
      explanationHinglish: 'Power print kiya.',
      memorySnapshot: { ans: 8 },
      consoleOutput: '8',
      animationEvent: { type: 'PRINT_VALUE', variableName: 'ans', outputValue: 8 },
    }
  ],
};